name: ecommerce
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

#-----------Packages-------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: 
  intl:
  logger:
  url_launcher:
  get_storage:
  flutter_native_splash:

  #Icons
  iconsax:
  cupertino_icons: ^1.0.8


  # State Management
  get:

#-------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #-------------LOCAL ASSETS----------------------#
  assets:
    - assets/logos/
    - assets/logos/yamarkets_dark_logo.png
    - assets/logos/yamarkets_light_logo.png
    - assets/icons/

